### PR TITLE
Upgrading Candybar + making it fully FOSS

### PR DESCRIPTION
**Pull request by Donnnno**
Hi,

I've taken the time to update your icon pack to Candybar-FOSS because the billing and license checking components weren't of use anyways.

With the lisence checking removed, it is ready to be added to F-Droid

image

https://github.com/PapirusDevelopmentTeam/papirus_icons/issues/7

### CODE REVIEW

**Comment by Donnnno** [comment]
reminder :)

**Review by BEEDELLROKEJULIANLOCKHART — APPROVED** [review]

**Comment by varlesh** [comment]
Users not interested this project. Now it's freezed :(

**Comment by Donnnno** [comment]
> Users not interested this project. Now it's freezed :(

Sad, I think a part of the problem is that it's kinda hard to find, an inclusion in F-Droid would help a lot with that. 

This PR does everything to make it work, without breaking anything that's already in the pack. If you'd like, I could also make a request for packaging in F-Droid for you :)

**Comment by varlesh** [comment]
You can fork it and publish on F-Droid, i have nothing against :)

**Comment by varlesh** [comment]
Merged. I'm not planned update this project on near future. Please know about this

**Pull request merged**
